server:
  port: 9001

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: xxxxxx
    username: root
    password: xxxxxx
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      validation-query: select 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true

  servlet:
    multipart:
      #文件大小
      max-file-size: 2MB
      #请求大小（含表单）
      max-request-size: 2MB

  redis:
    host: xxxxx
    password: xxxxx
  rabbitmq:
    host: xxxxxx
    username: xxxx
    password: xxxxx

  #邮件系统
  mail:
    host: smtp.qq.com
    port: 465
    username: xxxxxxxx
    #授权码
    password: xxxxxx
    protocol: smtp
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          # 如果是用 SSL 方式，需要配置如下属性,使用qq邮箱的话需要开启
          ssl:
            enable: true
            require: true
            # 邮件接收时间的限制，单位毫秒
          timeout: 10000
          # 连接时间的限制，单位毫秒
          connectiontimeout: 10000
          # 邮件发送时间的限制，单位毫秒
          writetimeout: 10000

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: -1
      logic-not-delete-value: 0
      logic-delete-field: flag
  configuration:
    #控制台打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #驼峰命名
    map-underscore-to-camel-case: true
    #缓存全局开关
    cache-enabled: true
    #延时加载
    lazy-loading-enabled: true
    #演示加载
    multiple-result-sets-enabled: false

  #扫描枚举配置包
  type-enums-package: com.team10.ojbattle.common.enums

http_pool:
  max_total: 200
  default_max_per_route: 100
  connect_timeout: 5000
  connection_request_timeout: 1000
  socket_timeout: 65000
  validate_after_inactivity: 2000

token: YOUR_TOKEN_HERE
server_base_url: http://118.178.253.239:12358


