server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oj_battle?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      validation-query: select 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true

  servlet:
    multipart:
      #文件大小
      max-file-size: 2MB
      #请求大小（含表单）
      max-request-size: 2MB


  redis:
    host: 118.178.253.239

  rabbitmq:
    host: 118.178.253.239
    username: guest
    password: guest

  #邮件系统
  mail:
    host: smtp.qq.com
    port: 465
    username: 853804445@qq.com
    #授权码
    password: jgictaccuwrzbcbi
    protocol: smtp
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          # 如果是用 SSL 方式，需要配置如下属性,使用qq邮箱的话需要开启
          ssl:
            enable: true
            require: true
            # 邮件接收时间的限制，单位毫秒
          timeout: 10000
          # 连接时间的限制，单位毫秒
          connectiontimeout: 10000
          # 邮件发送时间的限制，单位毫秒
          writetimeout: 10000
  #redis锁
  klock:
    address: 118.178.253.239:6379

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: -1
      logic-not-delete-value: 0
      logic-delete-field: flag
  configuration:
    #控制台打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #驼峰命名
    map-underscore-to-camel-case: true
    #缓存全局开关
    cache-enabled: true
    #延时加载
    lazy-loading-enabled: true
    #演示加载
    multiple-result-sets-enabled: true
  type-enums-package: com.team10.ojbattle.common.myenum



