server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.178.253.239:3306/oj_battle?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

  redis:
    host: 118.178.253.239

  rabbitmq:
    host: 118.178.253.239
    username: guest
    password: guest

  mail:
    host: smtp.qq.com
    port: 465
    username: 853804445@qq.com
    #授权码
    password: jgictaccuwrzbcbi
    protocol: smtp
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          # 如果是用 SSL 方式，需要配置如下属性,使用qq邮箱的话需要开启
          ssl:
            enable: true
            require: true
            # 邮件接收时间的限制，单位毫秒
          timeout: 10000
          # 连接时间的限制，单位毫秒
          connectiontimeout: 10000
          # 邮件发送时间的限制，单位毫秒
          writetimeout: 10000
  #redis锁
  klock:
    address: 118.178.253.239:6379

mybatis-plus:
  configuration:
    #控制台打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #驼峰命名
    map-underscore-to-camel-case: true
    #缓存全局开关
    cache-enabled: true
    #延时加载
    lazy-loading-enabled: true
    #演示加载
    multiple-result-sets-enabled: true
  global-config:
    db-config:
      id-type: id_worker_str



#加密的盐
salt: coding-study

#过期时间，现在设了一周
expiration-time: 3600000L * 24 * 7

